### ISSUE TITLE
コントローラーについて

### ISSUE THREAD

**Issue by mst-mkt** [INIAD-Developers/Mugen-sweeper#66]
コントローラー画面の配置やデザインについてチーム内で意見がまとまっていないのでissueを立てます。

## 配置について
自分は以下のような全体にマインスイーパーの画面でその前面にボタンがあるという認識でしたが、

https://github.com/INIAD-Developers/Mugen-sweeper/assets/131662659/ac268c96-59f0-4097-b9ed-646e5eaba888

yossuliは以下のような内部に画面のようなものがあるレイアウトにしたいそうです
![image](https://github.com/INIAD-Developers/Mugen-sweeper/assets/131662659/034cb5a0-076f-4adf-9d2e-f0d47ecb277c)

## デザインについて

上の2つの例をのように、Minesweeper本家のデザインにするのか独自の配色などにするのか、複数の意見があったので決める必要がると思います。
個人的な意見にはなりますが自分は本家のデザインのほうが好みです。

---
参考PR: #65

**Comment by yossuli** [comment]
僕の主張は
- 配色は正直なんでも良い(というかけいとのCSSだけで動かす方法のほうが滑らかだし移動のアニメーションがつくから優れていると思う)
- 全画面か3DSっぽい感じかもどっちでもいい。ただ、FPSとかと比べ、グラフィックスが綺麗な訳ではなく、どちらかというとレトロな感じだなと思い、3DSを参考にした配置にしたという経緯がある。
- マインスーイーパーというゲームが、地雷を踏まないように気を付けながら地雷のないマスを開けて行くというゲームである以上、プレイヤーが旗を立てるために地雷の上を歩くという行為を避けたいという思いがある。そのためにプレイヤーのいるマスと、旗を置いたり、掘ったりできるマスを分けている

**Comment by bondrewd-iniad** [comment]
スマホで操作性やUXを確認しましたか？

**Comment by yossuli** [comment]
まだ接続に成功していないです

**Comment by bondrewd-iniad** [comment]
展示の根幹なのでIssue作って早期に解決すべき
グラディウスも同じ問題を抱えているはず

そのあとスマホで両方みんなに試してもらえばどちらが良いUIかわかる
